# Generated by Django 4.1.6 on 2023-03-28 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PFapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='languages',
            field=models.CharField(default='English', max_length=300),
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='los',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='skills',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
