# Generated by Django 4.1.6 on 2023-03-28 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PFapp', '0002_employeeuser_languages_employeeuser_los_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='los',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
