# Generated by Django 4.1.6 on 2023-04-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PFapp', '0003_projectrole_los'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationDate', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFapp.employeeuser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFapp.projectrole')),
            ],
        ),
    ]
